version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:cached
    ports:
      - "9000:9000"

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      -  "3306:3306"
    volumes:
      -  ./db:/var/lib/mysql:cached
      -  ./my_conf:/etc/mysql/conf.d:cached
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      -  "8080:80"
    volumes:
      -  ./src:/var/www/html:cached
      -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      -  php
      -  mysql